---
sudo: required
language: python
python: "2.7"

dist: trusty

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
      - python3.5

before_install:
  - env
  - set -x
  - echo '[all]' | tee hosts
  - |
    for i in 5 6 7; do
      echo centos$i | tee -a hosts
      # runlevel(8) hack. centos5's runlevel(8) needs to execute /sbin/init
      docker run --name centos$i -di centos:$i /sbin/init
      if [ $i = 5 ]; then
        docker exec centos$i yum install -y python-simplejson
      fi
      docker exec centos$i cat /etc/redhat-release
    done

install:
  - SITE_PACKAGES_DIR=$(pip --version | awk '{print $4}')
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
  - echo $SITE_PACKAGES_DIR
  - cat tests/patch-lib::ansible::template::__init__.py | (cd "$SITE_PACKAGES_DIR"; patch -p0)
  - ansible --version
  - printf '[defaults]\nroles_path=../:tests/roles' | tee ansible.cfg
  - cat hosts

script:
  - python2.4 -m compileall -fq library
  - python2.6 -m compileall -fq library
  - python2.7 -m compileall -fq library
  - python3.5 -m compileall -fq library
  - ansible-validate-modules library || true
  #- ./test-docs.sh core
  - ansible-playbook -i hosts tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

